# Generated by Django 4.2.7 on 2025-12-16 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='shop_address',
            field=models.TextField(default='123 Gold Market, Gemstone Lane, Mumbai - 400001'),
        ),
        migrations.AddField(
            model_name='bill',
            name='shop_gstin',
            field=models.CharField(blank=True, help_text='GSTIN number', max_length=15),
        ),
        migrations.AddField(
            model_name='bill',
            name='shop_name',
            field=models.CharField(default='SHREE JEWELLERS', max_length=200),
        ),
        migrations.AddField(
            model_name='billitem',
            name='item_code',
            field=models.CharField(blank=True, help_text='Item code/SKU', max_length=50),
        ),
        migrations.AddField(
            model_name='billitem',
            name='making_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Making charges/Labour charges', max_digits=12),
        ),
    ]
