# Generated by Django 4.2.7 on 2025-12-16 16:35

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_shop_address_bill_shop_gstin_bill_shop_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='fine_gold',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='making_charges',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='rate_per_gram',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='tunch',
        ),
        migrations.AddField(
            model_name='bill',
            name='ci_balance_cr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CI Balance Cr', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='ci_balance_dr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='CI Balance Dr', max_digits=12),
        ),
        migrations.AddField(
            model_name='bill',
            name='ci_balance_gold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='CI Balance Gold', max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='g_fine',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='GFine (Gold Fine)', max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='item_number',
            field=models.CharField(blank=True, help_text='Item number (e.g., 5570, 5560)', max_length=20),
        ),
        migrations.AddField(
            model_name='billitem',
            name='item_type',
            field=models.CharField(choices=[('S', 'S - New Gold'), ('REC', 'REC - Received Old Gold')], default='S', max_length=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='labour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Labour charges', max_digits=12),
        ),
        migrations.AddField(
            model_name='billitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('7000.00'), help_text='Rate per gram', max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='s_fine',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='SFine', max_digits=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='tunch_wstg',
            field=models.DecimalField(decimal_places=2, default=Decimal('91.60'), help_text='Tunch wastage percentage (e.g., 78.00, 89.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='bill',
            name='shop_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='shop_name',
            field=models.CharField(default='ROHTASH SARRAF', max_length=200),
        ),
    ]
