# Generated by Django 4.2.7 on 2025-12-19 08:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0005_silverrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='material_type',
            field=models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('bar', 'Bar')], default='gold', help_text='Material type: Gold, Silver, or Bar', max_length=10),
        ),
        migrations.CreateModel(
            name='BarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_gram', models.DecimalField(decimal_places=2, help_text='Bar rate per gram', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'get_latest_by': 'updated_at',
            },
        ),
    ]
